CREATE TABLE IF NOT EXISTS models (
  provider TEXT NOT NULL,
  name TEXT NOT NULL,
  active INTEGER NOT NULL CHECK (active IN (0, 1)),
  position INTEGER NOT NULL DEFAULT 1000,
  PRIMARY KEY (provider, name)
);
INSERT OR IGNORE INTO models (provider, name, active, position) VALUES
('chatgpt', 'GPT-6 Astra', 1, 0),
('chatgpt', 'GPT-6.1 Sol', 1, 1),
('chatgpt', 'GPT-6 Sol', 1, 2),
('chatgpt', 'GPT-6 Luna', 1, 3),
('chatgpt', 'GPT-5.6 Sol', 1, 4),
('chatgpt', 'GPT-5.6 Terra', 1, 5),
('chatgpt', 'GPT-5.6 Luna', 1, 6),
('chatgpt', 'GPT-5.5', 1, 7),
('claude', 'Claude Opus 5.5', 1, 0),
('claude', 'Claude Sonnet 5.5', 1, 1),
('claude', 'Claude Haiku 5.5', 1, 2),
('claude', 'Claude Opus 4.7', 1, 3),
('claude', 'Claude Sonnet 4.6', 1, 4),
('claude', 'Claude Haiku 4.5', 1, 5),
('copilot', 'GPT-6.1 Sol', 1, 0),
('copilot', 'GPT-6 Sol', 1, 1),
('copilot', 'Claude Opus 5.5', 1, 2),
('copilot', 'Claude Sonnet 5.5', 1, 3),
('copilot', 'Gemini 3.8 Flash', 1, 4),
('copilot', 'Grok 4.7', 1, 5),
('cursor', 'Auto', 1, 0),
('cursor', 'Composer', 1, 1),
('cursor', 'Claude Opus 5.5', 1, 2),
('cursor', 'Claude Sonnet 5.5', 1, 3),
('cursor', 'GPT-6.1 Sol', 1, 4),
('cursor', 'Gemini 3.8 Flash', 1, 5),
('deepseek', 'DeepSeek V4.1 Flash', 1, 0),
('deepseek', 'DeepSeek V4 Pro', 1, 1),
('deepseek', 'DeepSeek V4 Flash', 1, 2),
('gemini', 'Gemini 3.8 Flash', 1, 0),
('gemini', 'Gemini 3.7 Flash', 1, 1),
('gemini', 'Gemini 3.5 Flash', 1, 2),
('gemini', 'Gemini 3.1 Pro', 1, 3),
('gemini', 'Gemini 2.5 Pro', 1, 4),
('gemini', 'Gemini 2.5 Flash', 1, 5),
('grok', 'Grok 4.7', 1, 0),
('grok', 'Grok 4.6', 1, 1),
('grok', 'Grok 4.5', 1, 2),
('grok', 'Grok 4.3', 1, 3),
('kimi', 'Kimi K3', 1, 0),
('kimi', 'Kimi K2.7 Code', 1, 1),
('kimi', 'Kimi K2.6', 1, 2),
('kimi', 'Kimi K2.5', 1, 3),
('kimi', 'Kimi K2', 1, 4),
('mistral', 'Mistral Large 4', 1, 0),
('mistral', 'Mistral Medium 3.5', 1, 1),
('mistral', 'Mistral Small 3.2', 1, 2),
('mistral', 'Codestral 25.08', 1, 3),
('mistral', 'Devstral Small', 1, 4),
('zai', 'GLM-5.3', 1, 0),
('zai', 'GLM-5.2', 1, 1),
('zai', 'GLM-5.1', 1, 2),
('zai', 'GLM-5', 1, 3),
('zai', 'GLM-4.7', 1, 4),
('zai', 'GLM-4.7-Flash', 1, 5);
